### ISSUE TITLE
Use `.svg` instead of `.psd`

### ISSUE THREAD

**Issue by aym-i** [DillanV/Ultimate-HOI4-GFX#3]
I highly recommend that you use `.svg` instead of `.psd`, because PS is payware and `.svg` is highly customisable :)

**Comment by Astram2k22** [comment]
psd is PhotoShop Document, most people who don't wanna pay for photoshop will use GIMP or PDN, i believe both can go into DirectDraw Surface (.dds) which is what hoi4 uses

**Comment by aym-i** [comment]
Hey! Just saw ur comment, thx for the reply but i abondoned hoi 4 modding a long while ago so this will be closed
